import im1 from '../assets/soup.jpg'
import im2 from '../assets/tomato.jpg'
import im3 from '../assets/chocolate.jpg'
import tarte from '../assets/tarte.jpg'
import saumon from '../assets/saumon.jpg'
import dessert from '../assets/desser.jpg'
import brioche from "../assets/Brioche.jpg"
import chouquettes from "../assets/Chouquettes.jpg"
import cookies from "../assets/cookies.jpg"
import Sirop from "../assets/Sirop.jpg"
import tisane from "../assets/tisane.jpg"
import chips from "../assets/chips.jpg"
import Gommage from "../assets/Gommage.jpg"
import Bouillon from "../assets/Bouillon.jpg"
import Hachi from "../assets/Hachi.jpg"
import rapide from "../assets/rapide.jpg"
import entrées from "../assets/entrées.png"
import plats from "../assets/plats.png"
import desserts from "../assets/desserts.png"
import aperitifs from "../assets/aperitifs.png"
import muffins from '../assets/muffins.jpg'
import bûchessaumon from '../assets/bûches-saumon.jpg'
import carbonara from '../assets/carbonara.jpg'
import bolognaise from '../assets/bolognaise.jpg'
import cabillaud from '../assets/cabillaud.jpg'
import Sauce from '../assets/Sauce.jpg'
import Papillottescumin from '../assets/Papillottes-cumin.jpg'
import Saumonamandes from '../assets/Saumon-amandes.jpg'
import pouletmoutarde from '../assets/poulet-moutarde.jpg'
import lentillescorail from '../assets/lentilles-corail.jpg'
import Soupecourgettecurry from '../assets/Soupe-courgette-curry.jpg'
import Courgettesviandehachée from '../assets/Courgettes-viande-hachée.jpg'
import Terrine from '../assets/Terrine.jpg'
import Verrines from '../assets/Verrines.jpg'
/*
const News = [
  {
    id: 1,
    //imageSource: "/images/burger-bacon-egg.png",
    title: "Comment conserver les courgettes?",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    //imageSource: "/images/burger-vegan.png",
    title: "Comment conserver les tomates?",
    price: 5.4985,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    //imageSource: "/images/burger3.png",
    title: "Faut-il décongeler sa viande avant de la cuire ?",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    //imageSource: "/images/drink1.png",
    title: "Mauvaises odeurs dans une gourde, comment s'en débarrasser?",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    //imageSource: "/images/drink2.png",
    title: "Astuces efficaces pour éviter que la ratatouille soit trop liquide",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    //imageSource: "/images/drink2.png",
    title: "Pourquoi a-t-on moins d'appétit quand il fait chaud ?",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    //imageSource: "/images/drink2.png",
    title: "L'eau citronnée : un trésor pour votre santé",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 8,
    //imageSource: "/images/drink2.png",
    title: "Comment cuisiner un melon fade et sans goût?",
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
] 
*/

export const fakeMenu = {
  Category : [
    {
      id: 1,
      title: "Rapide",
      imageSource: rapide,
      recettes: [
        {
          id: 1,
          imageSource: carbonara,
          title: 'Pâtes à la carbonara',
          preparationTime: 5,
          cookingTime: 15,
          ingredients: [
            { name: 'Spaghettis', quantity: 400, unit: 'g' },
            { name: 'Guanciale (joue de porc) ou pancetta', quantity: 200, unit: 'g' },
            { name: "Jaunes d'œufs", quantity: 3,  },
            { name: 'Parmesan', quantity: 100, unit: 'g' },
            { name: 'Poivre', quantity: 1, unit: 'c' },
          ],
          instructions: [
            "1. Faire bouillir dans une casserole un grand volume d'eau.",
            "2. Plonger les pâtes dans l'eau et faire cuire 9-10 min selon le type de pâtes.",
            "3. Pendant ce temps, couper le guanciale (joue de porc) ou la pancetta en gros lardons d'1cm de côté. Cuire la viande dans une poêle, sans ajout de matière grasse.",
            "4. Dès que les pâtes sont cuites, les égoutter en gardant un peu d'eau de cuisson dans un bol. Verser les pâtes dans la poêle avec le guanciale ou la pancetta (feu éteint). Bien mélanger. Ensuite, verser la préparation dans un plat.",
            "5. Dans un bol, mélanger les 3 jaunes d'œufs en ajoutant petit à petit un peu d'eau de cuisson des pâtes jusqu'à obtenir une sauce crémeuse.",
            "6. Bien mélanger le tout et surtout bien poivrer. C'est le poivre qui donnera du goût au plat.",
            "7. Ajouter le parmesan.",
            "8. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 2,
          imageSource: bolognaise,
          title: 'Spaghettis à la bolognaise',
          preparationTime: 5,
          cookingTime: 15,
          ingredients: [
            { name: 'Spaghettis', quantity: 400, unit: 'g' },
            { name: 'de boeuf hâché', quantity: 300, unit: 'g' },
            { name: 'de tomates pelées', quantity: 800, unit: 'g' },
            { name: 'de coulis de tomate', quantity: 200, unit: 'g' },
            { name: 'de parmesan ou emmental râpé', quantity: 100, unit: 'g' },
            { name: "petit Oignon", quantity: 1,  },
            { name: "à soupe d'huile d'olive (ou tournesol)", quantity: 1, unit: 'cuillère' },
            { name: "de sucre en poudre", quantity: 1, unit: 'cuillère' },
            { name: "de sel", quantity: 1, unit: 'pincée' },
            { name: "de poivre", quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Épluchez et émincez les oignons en petits cubes.",
            "2. Chauffez une poêle, ajoutez un filet d'huile, puis ajoutez les oignons en les faisant revenir à feu vif jusqu'à ce qu'ils colorent légèrement.",
            "3. Ajoutez la viande hachée, salez et poivrez et faites-la cuire à feu vif pendant environ 5 min.",
            "4. Versez ensuite les tomates pelées, le sucre en poudre et laissez mijoter le tout à feu doux pendant environ 10 min tout en remuant la préparation.",
            "5. Pendant ce temps, plongez les pâtes dans l'eau et faites-les cuire 9-10 min selon le temps indiqué sur le paquet.",
            "6. Quand les spaghettis sont cuits, égouttez-les et disposez-les dans des assiettes creuses sans attendre.",
            "7. Versez la sauce bolognaise sur les spaghettis et saupoudrez de parmesan râpé.",
            "8. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 3,
          imageSource: cabillaud,
          title: 'Papillotes de cabillaud',
          preparationTime: 15,
          cookingTime: 30,
          ingredients: [
            { name: 'filets de cabillauds', quantity: 2, },
            { name: 'demi poivron vert', quantity: 1,  },
            { name: 'demi poivron rouge', quantity: 1,  },
            { name: 'tomate', quantity: 1,  },
            { name: 'branches de thyms', quantity: 2,  },
            { name: 'Curry en poudre', quantity: 1, unit: 'pincée' },
            { name: "Huile d'olive", quantity: 2, unit: 'CS' },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Poivre', quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Lavez, épépinez et coupez en petits dés les poivrons et la tomate.",
            "2. Disposez 2 feuilles de papier sulfurisé sur le plan de travail, posez au centre de chaque feuille un filet de cabillaud.",
            "3. Salez, poivrez, ajoutez le curry selon vos goûts, puis répartissez les légumes.",
            "4. Nappez chaque filet d'une cuillère à café d'huile d'olive, déposez une branche de thym et refermez bien les papillotes en roulant les bords des feuilles de papier pour que ce soit bien hermétique.",
            "5. Déposez les papillotes dans un plat allant au four et enfournez à 30 min.",
            "6. Astuce : avec ce mode de cuisson, les poivrons sont encore un peu croquants. Si vous les voulez plutôt fondants, faites-les cuire dans une poêle avant de dresser vos papillotes.",
            "7. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 4,
          imageSource: Sauce,
          title: 'Sauce pour cabillaud',
          preparationTime: 10,
          cookingTime: 10,
          ingredients: [
            { name: 'filets de cabillauds', quantity: 4, },
            { name: "moutarde à l'ancienne", quantity: 20, unit: 'g' },
            { name: 'échalote', quantity: 1, },
            { name: 'de beurre', quantity: 10, unit: 'g' },
            { name: 'de crème liquide', quantity: 20, unit: 'cl' },
            { name: 'Jus de citron', quantity: 1, unit: 'CS' },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Poivre', quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Faites cuire les filets de cabillaud avec un filet d'huile dans une poêle, à feu moyen, quelques min. Retournez à mi-cuisson.",
            "2. Épluchez et ciselez finement l'échalote.",
            "3. Dans une casserole, faites fondre le beurre, puis ajoutez l'échalote et la cuire jusqu'à ce qu'elle soit translucide.",
            "4. Ajoutez ensuite la crème, la moutarde et bien mélanger.",
            "5. Assaisonnez votre sauce moutarde et laissez épaissir à feu doux pendant environ 10 min.",
            "6. Ajoutez le jus du 1/2 citron et laissez cuire encore quelques min. Votre sauce est prête : elle se sert bien chaude.",
            "7. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 5,
          imageSource: Saumonamandes,
          title: 'Saumon aux amandes',
          preparationTime: 15,
          cookingTime: 15,
          ingredients: [
            { name: 'pavés de saumon frais', quantity: 4,  },
            { name: 'de beurre', quantity: 2, unit: 'CC' },
            { name: "d'amandes effilées", quantity: 20, unit: 'g' },
            { name: "de crème semi-épaisse", quantity: 40, unit: 'g' },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Poivre', quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Faire cuire doucement les pavés de saumon dans une poêle antiadhésive puis les réserver au chaud. Essuyez la poêle, faire fondre la margarine et faire dorer les amandes effilées quelques instants.",
            "2. Ajoutez la crème, salez, poivrez. Déposez le poisson, faire réduire 5 min.",
            "3. Posez le saumon par-dessus, arrosez d'un filet d'huile d'olive, salez et poivrez de nouveau et ajoutez une tranche de citron.",
            "4.  Ce plat peut être accompagné de pâtes.",
            "5. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 6,
          imageSource: Papillottescumin,
          title: 'Papillottes de saumon au cumin',
          preparationTime: 15,
          cookingTime: 30,
          ingredients: [
            { name: 'portions de saumons', quantity: 2, },
            { name: 'carotte', quantity: 1, },
            { name: 'courgette', quantity: 1, },
            { name: 'Cumin en poudre', quantity: 1, unit: 'pincée' },
            { name: 'Herbes de Provence', quantity: 1, unit: 'CC' },
            { name: 'Jus de citron', quantity: 1, unit: 'CS' },
            { name: "Huile d'olive", quantity: 2, unit: 'CS' },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Poivre', quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Préchauffez le four à 180°C.",
            "2. Coupez la carotte et la courgette en fins bâtonnets, puis les répartir sur 2 feuilles de papier sulfurisé. Parsemez de cumin, herbes de Provence, sel, poivre.",
            "3. Posez le saumon par-dessus, arrosez d'un filet d'huile d'olive, salez et poivrez de nouveau et ajoutez une tranche de citron.",
            "4. Fermez la papillote de façon hermétique et cuire 25-30 min.",
            "5. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 7,
          imageSource: lentillescorail,
          title: 'Velouté de lentilles corail',
          preparationTime: 5,
          cookingTime: 20,
          ingredients: [
            { name: 'de lentilles corail', quantity: 250, unit: 'g' },
            { name: 'de curry en poudre', quantity: 2, unit: 'CC' },
            { name: 'bouillon de cube à la volaille', quantity: 1, },
          ],
          instructions: [
            "1. Chauffez de l'eau dans une grande casserole.",
            "2. Versez les lentilles corail, le bouillon de cube émietté et le curry dans la casserole.",
            "3. Laissez cuire environ 20 min à couvert.",
            "4. Une fois la préparation refroidie, mixez les lentilles. Si le velouté est trop épais, diluez-le avec de l'eau jusqu'à obtenir la consistance désirée.",
            "5. Réchauffez le velouté juste avant de le déguster. Servez bien chaud.",
            "6. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 8,
          imageSource: pouletmoutarde,
          title: 'Escalopes de poulet à la moutarde',
          preparationTime: 10,
          cookingTime: 20,
          ingredients: [
            { name: "aiguillettes de poulets", quantity: 2,  },
            { name: "d'eau", quantity: 250, unit: 'ml' },
            { name: "de moutarde", quantity: 1, unit: 'CS' },
            { name: 'carotte', quantity: 1, },
            { name: "Huile d'olive", quantity: 1, unit: 'CS' },
            { name: 'de poivre', quantity: 1, unit: 'pincée' },
            { name: 'de sel', quantity: 1, unit: 'pincée' },
          ],
          instructions: [
            "1. Faites revenir dans une poêle, avec l'huile d'olive, les aiguillettes de poulet.",
            "2. Préparez les tagliatelles de carottes : épluchez et rincez la carotte, puis à l'aide d'un économe, réalisez des tagliatelles. Les faire revenir quelques min dans l'huile d'olive. Salez et poivrez.",
            "3. Diluez dans 1/2 verre d'eau chaude la moutarde et versez le tout dans la poêle. Laissez chauffer environ 10 min, puis ajoutez la crème. Salez et poivrez.",
            "4. Ajoutez les tagliatelles de carottes. Servez immédiatement.",
            "5. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 9,
          imageSource: Courgettesviandehachée,
          title: 'Courgettes à la viande hachée',
          preparationTime: 20,
          cookingTime: 20,
          ingredients: [
            { name: 'courgette', quantity: 1, },
            { name: 'de persil', quantity: 1, unit: 'pincée' },
            { name: 'de poivre', quantity: 1, unit: 'pincée' },
            { name: 'de sel', quantity: 1, unit: 'pincée' },
            { name: 'de gruyère râpé', quantity: 50, unit: 'g' },
            { name: 'de viande hachée', quantity: 500, unit: 'g' },
            { name: 'de coulis de tomates', quantity: 400, unit: 'g' },
            { name: "d'ail", quantity: 1, unit: 'gousse' },
          ],
          instructions: [
            "1. Couper les courgettes en rondelles et les faire cuire 20 mn à la vapeur.",
            "2. Pendant ce temps, faire revenir 10 mn la viande hachée dans un peu de matière grasse. Ajouter le coulis de tomate, l'ail, le persil, le sel et le poivre. Laisser cuire encore 5 mn.",
            "3. Mélanger le tout. Saupoudrer de gruyère râpé.",
            "4. Peut s'accompagner de pâtes.",
            "5. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
        {
          id: 10,
          imageSource: Soupecourgettecurry,
          title: 'Soupe à la courgette et au curry',
          preparationTime: 30,
          cookingTime: 30,
          ingredients: [
            { name: 'de courgette', quantity: 1, unit: 'kg' },
            { name: 'oignon', quantity: 1, },
            { name: 'curry', quantity: 1, },
            { name: 'de poivre', quantity: 1, unit: 'pincée' },
            { name: "de sel", quantity: 1, unit: 'pincée' },
            { name: 'huile', quantity: 1, unit: 'CS' },
            { name: 'de pommes de terre', quantity: 300, unit: 'g' },
            { name: "d'ail", quantity: 1, unit: 'gousse' },
            { name: "bouillon de volaille", quantity: 1, unit: 'cube' },
          ],
          instructions: [
            "1. Découpez en cubes les courgettes et les pommes de terre épluchées. Coupez les oignons grossièrement.",
            "2. Préparez du bouillon de volaille (frais ou lyophilisé).",
            "3. Dans une cocotte, faites chauffez 2 cuillères à soupe d'huile. Quand celle ci est bien chaude, versez les oignons et l'ail et saupoudrez de curry.",
            "4. Remuez constamment, le temps que les oignons s'imprègnent de curry. Versez 1 l d'eau (y compris le bouillon).",
            "5. Ajoutez les pommes de terre et 5 à 10 mn plus tard, les dés de courgettes.",
            "6. Laissez cuire 20 min. La soupe ne doit pas bouillir. Salez et poivrez.",
            "7. Mixez (de préférence le plus possible, cette soupe est meilleure lisse). C'est prêt!",
            "8. À déguster tout de suite. Bon appétit!",
          ],
          isAvailable: true,
          isAdvertised: false,
        },
      ],
      description: "Recettes prêtes en moins de 20 minutes pour les jours pressés.",
      averagePreparationTime: 15, // en minutes
      exampleRecipe: "Tartines express au fromage frais",
      isFeatured: true,
    },
    {
      id: 2,
      title: "Entrées",
      imageSource: entrées,
      recettes: [
        {
            id: 1,
            imageSource: bûchessaumon,
            title: 'Mini bûches au saumon',
            preparationTime: 15,
            cookingTime: 15,
            ingredients: [
              { name: 'Tranches de pain de mies', quantity: 4, },
              { name: 'Kiris', quantity: 2,  },
              { name: "Tranches de saumon fumés", quantity: 2,  },
              { name: 'à soupe Graines de sésame', quantity: 1, unit: 'cuillère' },
            ],
            instructions: [
              "1. Étalez finement les tranches de pain de mie au rouleau à pâtisserie.",
              "2. Tartinez ensuite chaque tranche de kiri. Bien en étaler sur les bords du pain de mie car le kiri servira à sceller la bûche.",
              "3. Disposez sur chaque tranche de pain de mie une tranche de saumon fumé.",
              "4. Roulez chaque tranche de pain de mie sur elle-même en serrant bien, de façon à former des petites bûches.",
              "5. Serrez-les dans du film alimentaire et placez-les au réfrigérateur environ 20 min.",
              "6. Ensuite, sortez les mini bûches du réfrigérateur, enlevez le film, puis coupez chaque bûche en 3 parties égales.",
              "7. Ajoutez un peu de kiri sur le dessus, puis une pincée de graines de sésame.",
              "8. Cette recette peut être préparée à l'avance.",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 2,
            imageSource: Terrine,
            title: 'Terrine de Saint Jacques et saumon',
            preparationTime: 30,
            cookingTime: 15,
            ingredients: [
              { name: 'Noix de Saint Jacques', quantity: 8, },
              { name: 'Tranches de saumon fumés', quantity: 4,  },
              { name: "Crème fraiche", quantity: 10, unit: 'cl' },
              { name: 'à soupe Graines de sésame', quantity: 1, unit: 'cuillère' },
              { name: 'petite Échalotte', quantity: 1,  },
              { name: 'Feuilles de gélatines', quantity: 2,  },
              { name: 'Pavés de saumons', quantity: 2,  },
              { name: 'Lait (pour recouvrir les Saint Jacques)', quantity: 20, unit: 'cl' },
              { name: 'Estragon (surgelé ou en poudre)', quantity: 1, },
            ],
            instructions: [
              "1. Mettez 48h avant, dans du lait, vos coquilles St Jacques à décongeler dans un saladier.",
              "2. La veille :",
              "3. Faites bouillir de l'eau avec du sel et du poivre, puis éteignez le feu et mettez les saumons pendant 20 min à couvert.",
              "4. Pendant ce temps, faites chauffer à feu doux les coquilles avec le lait vanillé. 5 min après le début de l'ébullition, égouttez.",
              "5. Pendant la cuisson des coquilles, mettez les feuilles de gélatine dans un bol avec de l'eau tiède.",
              "6.  Dans un mixeur, mélangez le saumon avec l'échalote préalablement hachée, la crème, le sel, le poivre, l'estragon, les feuilles de gélatine ramollies, et mixez.",
              "7. Dans une terrine, étirez un film plastique de manière à le faire largement dépasser les bords (phase délicate, le fond doit être lisse car c'est celui qu'on présente).",
              "8. Ajoutez les tranches de saumon. Par-dessus les tranches, alternez une couche de Saint-Jacques et une couche de préparation de saumon.",
              "9. Répétez l'opération.",
              "10. Fermez le dessus avec le film plastique et réservez au frais pendant 24 h.",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 3,
            imageSource: Verrines,
            title: 'Terrine de Saint Jacques et saumon',
            preparationTime: 15,
            cookingTime: 15,
            ingredients: [
              { name: 'Citron', quantity: 1, },
              { name: 'Crème fraiche épaisse', quantity: 25, unit: 'cl' },
              { name: "Avocats", quantity: 2, },
              { name: 'Tranches de saumon fumés', quantity: 3, },
              { name: 'de sel', quantity: 1, unit: 'pincée'  },
              { name: 'de poivre', quantity: 1, unit: 'pincée' },
            
            ],
            instructions: [
              "1. Prélever la chair des avocats et la réduire en purée. Ajouter le jus d'un demi-citron au mélange afin de le parfumer et d'éviter qu'il noircisse.",
              "2. Détailler les tranches de saumon fumé en fines lanières et y verser quelques gouttes de citron.",
              "3. Mettre au fond d'un verre : la purée d'avocat au citron, puis quelques cuillères à café de crème fraîche, et terminer par quelques lanières de saumon fumé en les enroulant sur elles-mêmes. Ajouter une rondelle de citron pour décorer.",
              "4. Se déguste frais.",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
      ],
      description: "Des débuts de repas savoureux et variés, froids ou chauds.",
      averagePreparationTime: 20,
      exampleRecipe: "Velouté de courgettes au fromage",
      isFeatured: false,
    },
    {
      id: 3,
      title: "Plats",
      imageSource: plats,
      recettes: [
        {
            id: 1,
            imageSource: carbonara,
            title: 'Pâtes à la carbonara',
            preparationTime: 5,
            cookingTime: 15,
            ingredients: [
              { name: 'Spaghettis', quantity: 400, unit: 'g' },
              { name: 'Guanciale (joue de porc) ou pancetta', quantity: 200, unit: 'g' },
              { name: "Jaunes d'œufs", quantity: 3,  },
              { name: 'Parmesan', quantity: 100, unit: 'g' },
              { name: 'Poivre', quantity: 1, unit: 'c' },
            ],
            instructions: [
              "1. Faire bouillir dans une casserole un grand volume d'eau.",
              "2. Plonger les pâtes dans l'eau et faire cuire 9-10 min selon le type de pâtes.",
              "3. Pendant ce temps, couper le guanciale (joue de porc) ou la pancetta en gros lardons d'1cm de côté. Cuire la viande dans une poêle, sans ajout de matière grasse.",
              "4. Dès que les pâtes sont cuites, les égoutter en gardant un peu d'eau de cuisson dans un bol. Verser les pâtes dans la poêle avec le guanciale ou la pancetta (feu éteint). Bien mélanger. Ensuite, verser la préparation dans un plat.",
              "5. Dans un bol, mélanger les 3 jaunes d'œufs en ajoutant petit à petit un peu d'eau de cuisson des pâtes jusqu'à obtenir une sauce crémeuse.",
              "6. Bien mélanger le tout et surtout bien poivrer. C'est le poivre qui donnera du goût au plat.",
              "7. Ajouter le parmesan.",
              "8. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 2,
            imageSource: bolognaise,
            title: 'Spaghettis à la bolognaise',
            preparationTime: 5,
            cookingTime: 15,
            ingredients: [
              { name: 'Spaghettis', quantity: 400, unit: 'g' },
              { name: 'de boeuf hâché', quantity: 300, unit: 'g' },
              { name: 'de tomates pelées', quantity: 800, unit: 'g' },
              { name: 'de coulis de tomate', quantity: 200, unit: 'g' },
              { name: 'de parmesan ou emmental râpé', quantity: 100, unit: 'g' },
              { name: "petit Oignon", quantity: 1,  },
              { name: "à soupe d'huile d'olive (ou tournesol)", quantity: 1, unit: 'cuillère' },
              { name: "de sucre en poudre", quantity: 1, unit: 'cuillère' },
              { name: "de sel", quantity: 1, unit: 'pincée' },
              { name: "de poivre", quantity: 1, unit: 'pincée' },
            ],
            instructions: [
              "1. Épluchez et émincez les oignons en petits cubes.",
              "2. Chauffez une poêle, ajoutez un filet d'huile, puis ajoutez les oignons en les faisant revenir à feu vif jusqu'à ce qu'ils colorent légèrement.",
              "3. Ajoutez la viande hachée, salez et poivrez et faites-la cuire à feu vif pendant environ 5 min.",
              "4. Versez ensuite les tomates pelées, le sucre en poudre et laissez mijoter le tout à feu doux pendant environ 10 min tout en remuant la préparation.",
              "5. Pendant ce temps, plongez les pâtes dans l'eau et faites-les cuire 9-10 min selon le temps indiqué sur le paquet.",
              "6. Quand les spaghettis sont cuits, égouttez-les et disposez-les dans des assiettes creuses sans attendre.",
              "7. Versez la sauce bolognaise sur les spaghettis et saupoudrez de parmesan râpé.",
              "8. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 3,
            imageSource: cabillaud,
            title: 'Papillotes de cabillaud',
            preparationTime: 15,
            cookingTime: 30,
            ingredients: [
              { name: 'filets de cabillauds', quantity: 2, },
              { name: 'demi poivron vert', quantity: 1,  },
              { name: 'demi poivron rouge', quantity: 1,  },
              { name: 'tomate', quantity: 1,  },
              { name: 'branches de thyms', quantity: 2,  },
              { name: 'Curry en poudre', quantity: 1, unit: 'pincée' },
              { name: "Huile d'olive", quantity: 2, unit: 'CS' },
              { name: 'Sel', quantity: 1, unit: 'pincée' },
              { name: 'Poivre', quantity: 1, unit: 'pincée' },
            ],
            instructions: [
              "1. Lavez, épépinez et coupez en petits dés les poivrons et la tomate.",
              "2. Disposez 2 feuilles de papier sulfurisé sur le plan de travail, posez au centre de chaque feuille un filet de cabillaud.",
              "3. Salez, poivrez, ajoutez le curry selon vos goûts, puis répartissez les légumes.",
              "4. Nappez chaque filet d'une cuillère à café d'huile d'olive, déposez une branche de thym et refermez bien les papillotes en roulant les bords des feuilles de papier pour que ce soit bien hermétique.",
              "5. Déposez les papillotes dans un plat allant au four et enfournez à 30 min.",
              "6. Astuce : avec ce mode de cuisson, les poivrons sont encore un peu croquants. Si vous les voulez plutôt fondants, faites-les cuire dans une poêle avant de dresser vos papillotes.",
              "7. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 4,
            imageSource: saumon,
            title: "Saumon aux amandes",
            preparationTime: 15,
            cookingTime: 20,
            ingredients: [
            { name: "Filets de saumon", quantity: 2 },
            { name: "Amandes effilées", quantity: 50, unit: "g" },
            { name: "Beurre", quantity: 20, unit: "g" },
            { name: "Citron", quantity: 1 },
            { name: "Sel", quantity: 1, unit: "pincée" },
            { name: "Poivre", quantity: 1, unit: "pincée" },
            ],
            instructions: [
            "1. Préchauffez le four à 180°C.",
            "2. Placez les filets de saumon dans un plat.",
            "3. Salez, poivrez et arrosez de jus de citron.",
            "4. Parsemez d’amandes effilées et ajoutez le beurre fondu.",
            "5. Enfournez pour 15-20 minutes.",
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Plats"
        },
        {
            id: 5,
            imageSource: Papillottescumin,
            title: 'Papillottes de saumon au cumin',
            preparationTime: 15,
            cookingTime: 30,
            ingredients: [
              { name: 'portions de saumons', quantity: 2, },
              { name: 'carotte', quantity: 1, },
              { name: 'courgette', quantity: 1, },
              { name: 'Cumin en poudre', quantity: 1, unit: 'pincée' },
              { name: 'Herbes de Provence', quantity: 1, unit: 'CC' },
              { name: 'Jus de citron', quantity: 1, unit: 'CS' },
              { name: "Huile d'olive", quantity: 2, unit: 'CS' },
              { name: 'Sel', quantity: 1, unit: 'pincée' },
              { name: 'Poivre', quantity: 1, unit: 'pincée' },
            ],
            instructions: [
              "1. Préchauffez le four à 180°C.",
              "2. Coupez la carotte et la courgette en fins bâtonnets, puis les répartir sur 2 feuilles de papier sulfurisé. Parsemez de cumin, herbes de Provence, sel, poivre.",
              "3. Posez le saumon par-dessus, arrosez d'un filet d'huile d'olive, salez et poivrez de nouveau et ajoutez une tranche de citron.",
              "4. Fermez la papillote de façon hermétique et cuire 25-30 min.",
              "5. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 6,
            imageSource: pouletmoutarde,
            title: 'Escalopes de poulet à la moutarde',
            preparationTime: 10,
            cookingTime: 20,
            ingredients: [
              { name: "aiguillettes de poulets", quantity: 2,  },
              { name: "d'eau", quantity: 250, unit: 'ml' },
              { name: "de moutarde", quantity: 1, unit: 'CS' },
              { name: 'carotte', quantity: 1, },
              { name: "Huile d'olive", quantity: 1, unit: 'CS' },
              { name: 'de poivre', quantity: 1, unit: 'pincée' },
              { name: 'de sel', quantity: 1, unit: 'pincée' },
            ],
            instructions: [
              "1. Faites revenir dans une poêle, avec l'huile d'olive, les aiguillettes de poulet.",
              "2. Préparez les tagliatelles de carottes : épluchez et rincez la carotte, puis à l'aide d'un économe, réalisez des tagliatelles. Les faire revenir quelques min dans l'huile d'olive. Salez et poivrez.",
              "3. Diluez dans 1/2 verre d'eau chaude la moutarde et versez le tout dans la poêle. Laissez chauffer environ 10 min, puis ajoutez la crème. Salez et poivrez.",
              "4. Ajoutez les tagliatelles de carottes. Servez immédiatement.",
              "5. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
        {
            id: 7,
            imageSource: Courgettesviandehachée,
            title: 'Courgettes à la viande hachée',
            preparationTime: 20,
            cookingTime: 20,
            ingredients: [
              { name: 'courgette', quantity: 1, },
              { name: 'de persil', quantity: 1, unit: 'pincée' },
              { name: 'de poivre', quantity: 1, unit: 'pincée' },
              { name: 'de sel', quantity: 1, unit: 'pincée' },
              { name: 'de gruyère râpé', quantity: 50, unit: 'g' },
              { name: 'de viande hachée', quantity: 500, unit: 'g' },
              { name: 'de coulis de tomates', quantity: 400, unit: 'g' },
              { name: "d'ail", quantity: 1, unit: 'gousse' },
            ],
            instructions: [
              "1. Couper les courgettes en rondelles et les faire cuire 20 mn à la vapeur.",
              "2. Pendant ce temps, faire revenir 10 mn la viande hachée dans un peu de matière grasse. Ajouter le coulis de tomate, l'ail, le persil, le sel et le poivre. Laisser cuire encore 5 mn.",
              "3. Mélanger le tout. Saupoudrer de gruyère râpé.",
              "4. Peut s'accompagner de pâtes.",
              "5. À déguster tout de suite. Bon appétit!",
            ],
            isAvailable: true,
            isAdvertised: false,
        },
      ],
      description: "Des plats principaux pour tous les goûts, du classique au créatif.",
      averagePreparationTime: 35,
      exampleRecipe: "Lasagnes aux légumes de saison",
      isFeatured: true,
    },
    {
      id: 4,
      title: "Desserts",
      imageSource: desserts,
      recettes: [
        {
            id: 1,
            imageSource: brioche,
            title: "Brioche au sucre",
            preparationTime: 20,
            cookingTime: 30,
            ingredients: [
            { name: 'Farine', quantity: 500, unit: 'g' },
            { name: 'Levure boulangère', quantity: 1, unit: 'sachet' },
            { name: 'Sucre', quantity: 80, unit: 'g' },
            { name: 'Lait tiède', quantity: 200, unit: 'ml' },
            { name: 'Œufs', quantity: 3 },
            { name: 'Beurre', quantity: 100, unit: 'g' },
            { name: 'Sucre perlé', quantity: 2, unit: 'CS' },
            ],
            instructions: [
            "1. Mélanger la farine, la levure et le sucre.",
            "2. Ajouter les œufs et le lait tiède, pétrir la pâte.",
            "3. Incorporer le beurre mou et pétrir jusqu'à obtention d'une pâte lisse.",
            "4. Laisser lever 1h dans un endroit chaud.",
            "5. Dégazer la pâte, former une brioche et disposer dans un moule.",
            "6. Laisser lever à nouveau 30 min.",
            "7. Badigeonner de jaune d’œuf et parsemer de sucre perlé.",
            "8. Cuire à 180°C pendant 25 à 30 min.",
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Desserts"
        },
        {
            id: 2,
            imageSource: chouquettes,
            title: "Chouquettes au sucre perlé",
            preparationTime: 15,
            cookingTime: 20,
            ingredients: [
            { name: 'Eau', quantity: 250, unit: 'ml' },
            { name: 'Beurre', quantity: 100, unit: 'g' },
            { name: 'Farine', quantity: 150, unit: 'g' },
            { name: 'Œufs', quantity: 4 },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Sucre perlé', quantity: 2, unit: 'CS' },
            ],
            instructions: [
            "1. Porter l’eau, le beurre et le sel à ébullition.",
            "2. Hors du feu, ajouter la farine d’un coup et mélanger.",
            "3. Remettre sur feu doux et dessécher la pâte.",
            "4. Hors du feu, incorporer les œufs un à un.",
            "5. Former des petites boules sur une plaque.",
            "6. Saupoudrer de sucre perlé.",
            "7. Cuire à 200°C pendant 20 min jusqu’à ce qu’elles soient dorées.",
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Desserts"
        },
        {
            id: 3,
            imageSource: cookies,
            title: "Cookies aux pépites de chocolat",
            preparationTime: 10,
            cookingTime: 12,
            ingredients: [
            { name: 'Farine', quantity: 250, unit: 'g' },
            { name: 'Beurre mou', quantity: 125, unit: 'g' },
            { name: 'Sucre roux', quantity: 150, unit: 'g' },
            { name: 'Œufs', quantity: 1 },
            { name: 'Levure chimique', quantity: 1, unit: 'cc' },
            { name: 'Pépites de chocolat', quantity: 150, unit: 'g' },
            { name: 'Extrait de vanille', quantity: 1, unit: 'cc' },
            ],
            instructions: [
            "1. Préchauffer le four à 180°C.",
            "2. Mélanger le beurre et le sucre.",
            "3. Ajouter l'œuf et la vanille.",
            "4. Incorporer la farine, la levure et les pépites de chocolat.",
            "5. Former des petites boules sur une plaque de cuisson.",
            "6. Cuire pendant 10 à 12 min jusqu’à ce qu’ils soient dorés.",
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Desserts"
        },
        {
            id: 4,
            imageSource: im3,
            title: 'Mousse au chocolat',
            preparationTime: 20,
            cookingTime: 0,
            ingredients: [
            { name: 'Chocolat noir', quantity: 200, unit: 'g' },
            { name: 'Œufs', quantity: 6 },
            { name: 'Sel', quantity: 1, unit: 'pincée' },
            { name: 'Copeaux de chocolat (facultatif)', quantity: 1, unit: 'peu' },
            ],
            instructions: [
            '1. Séparer les blancs des jaunes d’œufs.',
            '2. Faire fondre le chocolat au bain-marie.',
            '3. Ajouter les jaunes au chocolat fondu, bien mélanger.',
            '4. Battre les blancs en neige avec le sel.',
            '5. Incorporer les blancs au mélange chocolaté sans casser les blancs.',
            '6. Répartir la mousse dans des verrines.',
            '7. Réfrigérer au moins 3 heures.',
            '8. Décorer avec des copeaux de chocolat (optionnel).'
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Desserts"
        },
        {
            id: 5,
            imageSource: dessert,
            title: "Fondant au chocolat",
            preparationTime: 15,
            cookingTime: 10,
            ingredients: [
            { name: "Chocolat noir", quantity: 200, unit: "g" },
            { name: "Beurre", quantity: 100, unit: "g" },
            { name: "Sucre", quantity: 80, unit: "g" },
            { name: "Farine", quantity: 50, unit: "g" },
            { name: "Œufs", quantity: 4 },
            ],
            instructions: [
            "1. Préchauffez le four à 200°C.",
            "2. Faites fondre le chocolat avec le beurre.",
            "3. Ajoutez le sucre, la farine, puis les œufs un à un.",
            "4. Versez dans des moules individuels beurrés.",
            "5. Faites cuire 10 minutes.",
            "6. Servez tiède avec une boule de glace vanille si désiré.",
            ],
            isAvailable: true,
            isAdvertised: false,
            category: "Desserts"
        },
      ],
      description: "Pour finir en douceur : gâteaux, crèmes, fruits revisités…",
      averagePreparationTime: 30,
      exampleRecipe: "Moelleux au chocolat fondant",
      isFeatured: true,
    },
    {
      id: 5,
      title: "Apéritifs",
      imageSource: aperitifs,
      recettes: [
          {
              id: 1,
              imageSource: bûchessaumon,
              title: 'Mini bûches au saumon',
              preparationTime: 15,
              cookingTime: 15,
              ingredients: [
                { name: 'Tranches de pain de mies', quantity: 4, },
                { name: 'Kiris', quantity: 2,  },
                { name: "Tranches de saumon fumés", quantity: 2,  },
                { name: 'à soupe Graines de sésame', quantity: 1, unit: 'cuillère' },
              ],
              instructions: [
                "1. Étalez finement les tranches de pain de mie au rouleau à pâtisserie.",
                "2. Tartinez ensuite chaque tranche de kiri. Bien en étaler sur les bords du pain de mie car le kiri servira à sceller la bûche.",
                "3. Disposez sur chaque tranche de pain de mie une tranche de saumon fumé.",
                "4. Roulez chaque tranche de pain de mie sur elle-même en serrant bien, de façon à former des petites bûches.",
                "5. Serrez-les dans du film alimentaire et placez-les au réfrigérateur environ 20 min.",
                "6. Ensuite, sortez les mini bûches du réfrigérateur, enlevez le film, puis coupez chaque bûche en 3 parties égales.",
                "7. Ajoutez un peu de kiri sur le dessus, puis une pincée de graines de sésame.",
                "8. Cette recette peut être préparée à l'avance.",
              ],
              isAvailable: true,
              isAdvertised: false,
          },
          {
              id: 2,
              imageSource: muffins,
              title: 'Muffins au chorizo',
              preparationTime: 30,
              cookingTime: 25,
              ingredients: [
                { name: 'poivron', quantity: 1, },
                { name: "d'huile d'olive", quantity: 2, unit: 'CS' },
                { name: "de sel", quantity: 1, unit: 'pincée' },
                { name: "de poivre", quantity: 1, unit: 'pincée' },
                { name: 'de chorizo fort', quantity: 200, unit: 'g' },
                { name: "d'ail", quantity: 4, unit: 'gousses' },
                { name: 'de farine', quantity: 250, unit: 'g' },
                { name: "de levure chimique", quantity: 1, unit: 'sachet'  },
                { name: "oeufs", quantity: 3,  },
                { name: "de lait", quantity: 10, unit: 'cl' },
                { name: "de tournesol", quantity: 10, unit: 'cl' },
              ],
              instructions: [
                "1. Couper le poivron en petits dés. Dans une poêle, le faire fondre à feu moyen dans l'huile d'olive.",
                "2. Pendant ce temps, couper le chorizo en rondelles puis en dés. Réserver.",
                "3. Peler et couper les gousses d'ail en petits morceaux. Les ajouter aux dés de poivrons. Assaisonner et continuer la cuisson à feu doux pour faire suer et ramollir l'ail.",
                "4. Préparer la pâte : mélanger la farine au sachet de levure. Battre les oeufs, rajouter le lait, l'huile et la farine en pluie. Saler.",
                "5. La pâte doit être légèrement épaisse : rectifier avec un peu de farine ou d'eau selon le résultat.",
                "6. Quand la garniture est cuite, bien la mélanger à la pâte, avec le chorizo. Remplir les moules à muffins aux 2/3. Cuire au four à 180°C (thermostat 6) pendant 25 min.",
              ],
              isAvailable: true,
              isAdvertised: false,
          },
      ],
      description: "Des idées originales et gourmandes à partager à l'apéro.",
      averagePreparationTime: 25,
      exampleRecipe: "Feuilletés au fromage et herbes",
      isFeatured: false,
    }
  ],
  
  CurrentNews: [
    {
      id: 1,
      imageSource: im1,
      title: 'Velouté de patates douces au curry',
      preparationTime: 10,
      cookingTime: 30,
      ingredients: [
        { name: 'Huile', quantity: 1, unit: 'CS' },
        { name: 'Oignon', quantity: 1 },
        { name: 'Gingembre frais râpé', quantity: 1, unit: 'CS' },
        { name: 'Curry en poudre', quantity: 1, unit: 'CS' },
        { name: 'Coriandre fraîche ciselée', quantity: 1, unit: 'petite poignée' },
        { name: 'Ail', quantity: 2, unit: 'gousses' },
        { name: 'Patate douce', quantity: 1000, unit: 'g' },
        { name: 'Bouillon de volaille', quantity: 1000, unit: 'ml' },
        { name: 'Lait de coco', quantity: 200, unit: 'ml' },
      ],
      instructions: [
        "1. Faire revenir l'oignon quelques minutes dans l'huile.",
        "2. Ajouter l'ail, le gingembre et la poudre de curry. Remuer.",
        "3. Mettre les morceaux de patates douces dans ce mélange.",
        "4. Verser le bouillon.",
        "5. Porter à ébullition puis laisser mijoter à couvert pendant 20 à 30 min.",
        "6. Enlever la casserole du feu.",
        "7. Laisser un peu refroidir.",
        "8. Mixer.",
        "9. Remettre sur le feu.",
        "10. Ajouter le lait de coco et la coriandre (en garder un peu pour la déco)."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Entrées",
    },
    {
      id: 2,
      imageSource: im2,
      title: 'Cocos de Paimpol à la tomate',
      preparationTime: 15,
      cookingTime: 45,
      ingredients: [
        { name: 'Haricots coco de Paimpol écossés', quantity: 500, unit: 'g' },
        { name: 'Huile d’olive', quantity: 2, unit: 'CS' },
        { name: 'Oignon', quantity: 1 },
        { name: 'Ail', quantity: 2, unit: 'gousses' },
        { name: 'Tomates', quantity: 2 },
        { name: 'Céleri branche', quantity: 1, unit: 'brin' },
        { name: 'Curcuma', quantity: 1, unit: 'pincée' },
        { name: 'Thym', quantity: 3, unit: 'brins' },
        { name: 'Laurier', quantity: 2, unit: 'feuilles' },
        { name: 'Eau', quantity: 700, unit: 'ml' },
        { name: 'Sel', quantity: 1, unit: 'pincée' }
      ],
      instructions: [
        '1. Écossez les haricots, rincez et égouttez-les.',
        '2. Pelez l’oignon et l’ail, coupez-les en dés. Pelez et coupez les tomates.',
        '3. Coupez le céleri, préparez le thym et le laurier.',
        '4. Chauffez l’huile d’olive dans une cocotte, ajoutez ail, oignon et céleri.',
        '5. Laissez cuire 5 min en remuant, ajoutez tomates, thym, laurier, curcuma.',
        '6. Compotez légèrement 5 min.',
        '7. Ajoutez les cocos, puis l’eau.',
        '8. Portez à ébullition, laissez cuire 30 min à frémissement.',
        '9. Salez, puis laissez cuire 10 min de plus.'
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Plats",
    },
    {
      id: 3,
      imageSource: im3,
      title: 'Mousse au chocolat',
      preparationTime: 20,
      cookingTime: 0,
      ingredients: [
        { name: 'Chocolat noir', quantity: 200, unit: 'g' },
        { name: 'Œufs', quantity: 6 },
        { name: 'Sel', quantity: 1, unit: 'pincée' },
        { name: 'Copeaux de chocolat (facultatif)', quantity: 1, unit: 'peu' },
      ],
      instructions: [
        '1. Séparer les blancs des jaunes d’œufs.',
        '2. Faire fondre le chocolat au bain-marie.',
        '3. Ajouter les jaunes au chocolat fondu, bien mélanger.',
        '4. Battre les blancs en neige avec le sel.',
        '5. Incorporer les blancs au mélange chocolaté sans casser les blancs.',
        '6. Répartir la mousse dans des verrines.',
        '7. Réfrigérer au moins 3 heures.',
        '8. Décorer avec des copeaux de chocolat (optionnel).'
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    }
  ],
  TopFood : [
    {
      id: 1,
      imageSource: tarte,
      title: "Tarte aux pommes",
      preparationTime: 25,
      cookingTime: 30,
      ingredients: [
        { name: "Pommes", quantity: 6 },
        { name: "Pâte brisée", quantity: 1 },
        { name: "Sucre", quantity: 1, unit: "sachet" },
        { name: "Beurre", quantity: 30, unit: "g" },
        { name: "Cannelle", quantity: 1, unit: "pincée" },
      ],
      instructions: [
        "1. Éplucher et découper en morceaux les pomme.",
        "2. Faire une compote : les mettre dans une casserole avec un peu d'eau (1 verre ou 2). Bien remuer. Quand les pommes commencent à ramollir, ajouter un sachet ou un sachet et demi de sucre vanillé. Ajouter un peu d'eau si nécessaire.",
        "3. Vous saurez si la compote est prête une fois que les pommes ne seront plus dures du tout. Ce n'est pas grave s'il reste quelques morceaux.",
        "4. Pendant que la compote cuit, éplucher et couper en quatre les deux dernières pommes, puis, couper les quartiers en fines lamelles (elles serviront à être posées sur la compote).",
        "5. Préchauffer le four à 210°C (thermostat 7).",
        "6. Laisser un peu refroidir la compote et étaler la pâte brisée dans un moule et la piquer avec une fourchette.",
        "7. Verser la compote sur la pâte et placer les lamelles de pommes en formant une spirale ou plusieurs cercles, au choix ! Disposer des lamelles de beurre dessus.",
        "8. Mettre au four et laisser cuire pendant 30 min. Surveiller la cuisson. Vous pouvez ajouter un peu de sucre vanillé sur la tarte pendant que çà cuit pour caraméliser un peu.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    },
    {
      id: 2,
      imageSource: saumon,
      title: "Saumon aux amandes",
      preparationTime: 15,
      cookingTime: 20,
      ingredients: [
        { name: "Filets de saumon", quantity: 2 },
        { name: "Amandes effilées", quantity: 50, unit: "g" },
        { name: "Beurre", quantity: 20, unit: "g" },
        { name: "Citron", quantity: 1 },
        { name: "Sel", quantity: 1, unit: "pincée" },
        { name: "Poivre", quantity: 1, unit: "pincée" },
      ],
      instructions: [
        "1. Préchauffez le four à 180°C.",
        "2. Placez les filets de saumon dans un plat.",
        "3. Salez, poivrez et arrosez de jus de citron.",
        "4. Parsemez d’amandes effilées et ajoutez le beurre fondu.",
        "5. Enfournez pour 15-20 minutes.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Plats"
    },
    {
      id: 3,
      imageSource: dessert,
      title: "Fondant au chocolat",
      preparationTime: 15,
      cookingTime: 10,
      ingredients: [
        { name: "Chocolat noir", quantity: 200, unit: "g" },
        { name: "Beurre", quantity: 100, unit: "g" },
        { name: "Sucre", quantity: 80, unit: "g" },
        { name: "Farine", quantity: 50, unit: "g" },
        { name: "Œufs", quantity: 4 },
      ],
      instructions: [
        "1. Préchauffez le four à 200°C.",
        "2. Faites fondre le chocolat avec le beurre.",
        "3. Ajoutez le sucre, la farine, puis les œufs un à un.",
        "4. Versez dans des moules individuels beurrés.",
        "5. Faites cuire 10 minutes.",
        "6. Servez tiède avec une boule de glace vanille si désiré.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    }
  ],
  Recipes : [
    {
      id: 1,
      imageSource: brioche,
      title: "Brioche au sucre",
      preparationTime: 20,
      cookingTime: 30,
      ingredients: [
        { name: 'Farine', quantity: 500, unit: 'g' },
        { name: 'Levure boulangère', quantity: 1, unit: 'sachet' },
        { name: 'Sucre', quantity: 80, unit: 'g' },
        { name: 'Lait tiède', quantity: 200, unit: 'ml' },
        { name: 'Œufs', quantity: 3 },
        { name: 'Beurre', quantity: 100, unit: 'g' },
        { name: 'Sucre perlé', quantity: 2, unit: 'CS' },
      ],
      instructions: [
        "1. Mélanger la farine, la levure et le sucre.",
        "2. Ajouter les œufs et le lait tiède, pétrir la pâte.",
        "3. Incorporer le beurre mou et pétrir jusqu'à obtention d'une pâte lisse.",
        "4. Laisser lever 1h dans un endroit chaud.",
        "5. Dégazer la pâte, former une brioche et disposer dans un moule.",
        "6. Laisser lever à nouveau 30 min.",
        "7. Badigeonner de jaune d’œuf et parsemer de sucre perlé.",
        "8. Cuire à 180°C pendant 25 à 30 min.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    },
    {
      id: 2,
      imageSource: chouquettes,
      title: "Chouquettes au sucre perlé",
      preparationTime: 15,
      cookingTime: 20,
      ingredients: [
        { name: 'Eau', quantity: 250, unit: 'ml' },
        { name: 'Beurre', quantity: 100, unit: 'g' },
        { name: 'Farine', quantity: 150, unit: 'g' },
        { name: 'Œufs', quantity: 4 },
        { name: 'Sel', quantity: 1, unit: 'pincée' },
        { name: 'Sucre perlé', quantity: 2, unit: 'CS' },
      ],
      instructions: [
        "1. Porter l’eau, le beurre et le sel à ébullition.",
        "2. Hors du feu, ajouter la farine d’un coup et mélanger.",
        "3. Remettre sur feu doux et dessécher la pâte.",
        "4. Hors du feu, incorporer les œufs un à un.",
        "5. Former des petites boules sur une plaque.",
        "6. Saupoudrer de sucre perlé.",
        "7. Cuire à 200°C pendant 20 min jusqu’à ce qu’elles soient dorées.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    },
    {
      id: 3,
      imageSource: cookies,
      title: "Cookies aux pépites de chocolat",
      preparationTime: 10,
      cookingTime: 12,
      ingredients: [
        { name: 'Farine', quantity: 250, unit: 'g' },
        { name: 'Beurre mou', quantity: 125, unit: 'g' },
        { name: 'Sucre roux', quantity: 150, unit: 'g' },
        { name: 'Œufs', quantity: 1 },
        { name: 'Levure chimique', quantity: 1, unit: 'cc' },
        { name: 'Pépites de chocolat', quantity: 150, unit: 'g' },
        { name: 'Extrait de vanille', quantity: 1, unit: 'cc' },
      ],
      instructions: [
        "1. Préchauffer le four à 180°C.",
        "2. Mélanger le beurre et le sucre.",
        "3. Ajouter l'œuf et la vanille.",
        "4. Incorporer la farine, la levure et les pépites de chocolat.",
        "5. Former des petites boules sur une plaque de cuisson.",
        "6. Cuire pendant 10 à 12 min jusqu’à ce qu’ils soient dorés.",
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Desserts"
    }
  ],
  SpecialRecipes : [
    {
      id: 1,
      imageSource: Sirop,
      title: "Sirop de queues de fraises",
      preparationTime: 10,
      cookingTime: 20,
      ingredients: [
        { name: "Queues de fraises", quantity: 200, unit: "g" },
        { name: "Eau", quantity: 500, unit: "ml" },
        { name: "Sucre", quantity: 150, unit: "g" },
        { name: "Jus de citron", quantity: 1, unit: "CS" },
      ],
      instructions: [
        "1. Rincer les queues de fraises.",
        "2. Les mettre dans une casserole avec l’eau et porter à ébullition.",
        "3. Laisser mijoter 15-20 min.",
        "4. Filtrer le mélange.",
        "5. Ajouter le sucre et le jus de citron.",
        "6. Porter de nouveau à ébullition pour épaissir légèrement.",
        "7. Verser dans une bouteille stérilisée."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Rapide"
    },
    {
      id: 2,
      imageSource: tisane,
      title: "Tisane de queues de cerises",
      preparationTime: 5,
      cookingTime: 10,
      ingredients: [
        { name: "Queues de cerises séchées", quantity: 2, unit: "CS" },
        { name: "Eau", quantity: 500, unit: "ml" }
      ],
      instructions: [
        "1. Faire bouillir l’eau.",
        "2. Ajouter les queues de cerises et laisser infuser 10 min.",
        "3. Filtrer et déguster chaud ou froid."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Rapide"
    },
    {
      id: 3,
      imageSource: chips,
      title: "Chips d'épluchures de pomme",
      preparationTime: 5,
      cookingTime: 25,
      ingredients: [
        { name: "Épluchures de pommes", quantity: 2, unit: "pommes" },
        { name: "Cannelle", quantity: 1, unit: "pincée" },
        { name: "Sucre", quantity: 1, unit: "CS" },
        { name: "Huile", quantity: 1, unit: "CS" }
      ],
      instructions: [
        "1. Préchauffer le four à 150°C.",
        "2. Mélanger les épluchures avec sucre, cannelle et huile.",
        "3. Étaler sur une plaque et enfourner 20-25 min en retournant à mi-cuisson.",
        "4. Laisser refroidir pour que ça croustille."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Rapide"
    },
    {
      id: 4,
      imageSource: Gommage,
      title: "Gommage pour le corps au marc de café",
      preparationTime: 5,
      cookingTime: 0,
      ingredients: [
        { name: "Marc de café", quantity: 2, unit: "CS" },
        { name: "Huile de coco", quantity: 1, unit: "CS" },
        { name: "Sucre", quantity: 1, unit: "CS" }
      ],
      instructions: [
        "1. Mélanger tous les ingrédients jusqu’à obtenir une pâte homogène.",
        "2. Appliquer sur peau humide en massant en mouvements circulaires.",
        "3. Rincer à l’eau tiède."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Apéritifs"
    },
    {
      id: 5,
      imageSource: Bouillon,
      title: "Bouillon de légumes avec épluchures",
      preparationTime: 10,
      cookingTime: 45,
      ingredients: [
        { name: "Épluchures de légumes (carottes, poireaux, etc.)", quantity: 500, unit: "g" },
        { name: "Eau", quantity: 1, unit: "L" },
        { name: "Ail", quantity: 2, unit: "gousses" },
        { name: "Thym", quantity: 2, unit: "brins" },
        { name: "Laurier", quantity: 1, unit: "feuille" },
        { name: "Sel", quantity: 1, unit: "pincée" },
        { name: "Poivre", quantity: 1, unit: "pincée" }
      ],
      instructions: [
        "1. Mettre les épluchures lavées dans une grande casserole.",
        "2. Ajouter l’eau, les herbes et les épices.",
        "3. Porter à ébullition puis mijoter à feu doux 45 min.",
        "4. Filtrer et conserver au frais."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Entrées"
    },
    {
      id: 6,
      imageSource: Hachi,
      title: "Hachis parmentier avec restes de pot-au-feu",
      preparationTime: 20,
      cookingTime: 30,
      ingredients: [
        { name: "Restes de viande de pot-au-feu", quantity: 300, unit: "g" },
        { name: "Pommes de terre", quantity: 600, unit: "g" },
        { name: "Lait", quantity: 100, unit: "ml" },
        { name: "Beurre", quantity: 30, unit: "g" },
        { name: "Oignon", quantity: 1 },
        { name: "Sel", quantity: 1, unit: "pincée" },
        { name: "Poivre", quantity: 1, unit: "pincée" }
      ],
      instructions: [
        "1. Éplucher et cuire les pommes de terre pour faire une purée avec lait, beurre, sel, poivre.",
        "2. Émincer l’oignon et le faire revenir.",
        "3. Ajouter la viande effilochée aux oignons.",
        "4. Disposer la viande dans un plat à gratin, recouvrir de purée.",
        "5. Enfourner à 180°C pendant 25-30 min."
      ],
      isAvailable: true,
      isAdvertised: false,
      category: "Entrées"
    }
  ]
};

